### ISSUE TITLE
media-sound/guitarix: waf doesn't work with python3

### ISSUE THREAD

**Issue by nick87720z** [jorgicio/jorgicio-gentoo#116]
waf version, shipped in guitarix sources, is not compatible with python3. When just runing ./waf configure, i get this error, which doesn't appear when using python2 ./waf configure:
```
Checking for jack >= 0.116.2             : yes 
Checking for jack session support        : Traceback (most recent call last):
  File "/home/nick87720z/dist/guitarix-0.36.1/wafadmin3/Utils.py", line 446, in recurse
    txt=readf(file_path,m='rU')
  File "/home/nick87720z/dist/guitarix-0.36.1/wafadmin3/Utils.py", line 409, in readf
    f=open(fname,m)
FileNotFoundError: [Errno 2] No such file or directory: '/home/nick87720z/dist/guitarix-0.36.1/wscript_configure'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./waf", line 161, in <module>
    Scripting.prepare(t, cwd, VERSION, wafdir)
  File "/home/nick87720z/dist/guitarix-0.36.1/wafadmin3/Scripting.py", line 105, in prepare
    prepare_impl(t,cwd,ver,wafdir)
  File "/home/nick87720z/dist/guitarix-0.36.1/wafadmin3/Scripting.py", line 98, in prepare_impl
    main()
  File "/home/nick87720z/dist/guitarix-0.36.1/wafadmin3/Scripting.py", line 133, in main
    fun(ctx)
  File "/home/nick87720z/dist/guitarix-0.36.1/wafadmin3/Scripting.py", line 172, in configure
    conf.sub_config([''])
  File "/home/nick87720z/dist/guitarix-0.36.1/wafadmin3/Configure.py", line 155, in sub_config
    self.recurse(k,name='configure')
  File "/home/nick87720z/dist/guitarix-0.36.1/wafadmin3/Utils.py", line 461, in recurse
    f(self)
  File "/home/nick87720z/dist/guitarix-0.36.1/wscript", line 669, in configure
    conf.check_cxx(fragment=code, msg="Checking for jack session support", define_name='HAVE_JACK_SESSION')
  File "/home/nick87720z/dist/guitarix-0.36.1/wafadmin3/Tools/config_c.py", line 411, in check_cxx
    return self.check(*k,**kw)ere 
  File "/home/nick87720z/dist/guitarix-0.36.1/wafadmin3/Tools/config_c.py", line 324, in check
    ret=self.run_c_code(*k,**kw)
  File "/home/nick87720z/dist/guitarix-0.36.1/wafadmin3/Tools/config_c.py", line 384, in run_c_code
    bld.compile()
  File "/home/nick87720z/dist/guitarix-0.36.1/wafadmin3/Build.py", line 170, in compile
    self.save()
  File "/home/nick87720z/dist/guitarix-0.36.1/wafadmin3/Build.py", line 116, in save
    cPickle.dump(data,file)
AttributeError: Can't pickle local object 'BuildContext.__init__.<locals>.node_class'
```

There is pull request awaiting.

**Comment by jorgicio** [comment]
Done. I just received a pull request to fix that and I did the rest. Now, this is fixed.
Please, resync and try again.
Thanks.
