### ISSUE TITLE
atom optional system-node

### ISSUE THREAD

**Issue by soredake** [jorgicio/jorgicio-gentoo#68]
Can you please make using a system-node and npm optional in atm ebuild? I have no way to install nodejs from portage because of libressl, and the use of symlinked node from home folder (installed from nvm) causes the error
```
module.js:597
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module version mismatch. Expected 48, got 46.
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/git-utils/lib/git.js:8:16)
    at Object.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/git-utils/lib/git.js:371:4)
    at Module._compile (module.js:570:32)
```

same: https://discuss.atom.io/t/upgrading-to-apm-1-11-4-and-encountering-libgit-errors/30901

**Comment by jorgicio** [comment]
Done, system-node USE-flag added. Try again and tell me what's going on.

**Comment by soredake** [comment]
```
#Fix apm binary to use the nodejs binary rather than the built-in
sed -i "s#\$binDir\/\$nodeBin#\$\(which \$nodeBin\)#" resources/app/apm/bin/apm
```
needs to be in if system-node

**Comment by jorgicio** [comment]
Done. Fixed. Try again.

**Comment by soredake** [comment]
Thanks!
