### ISSUE TITLE
multibootusb probably requires udisks 

### ISSUE THREAD

**Issue by fturco** [jorgicio/jorgicio-gentoo#91]
I installed `sys-boot/multibootusb-8.5.0` from your overlay but I can't start it because of a udisks-related error:

```
$ multibootusb
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib64/python3.6/site-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib64/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.freedesktop.UDisks2': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/scripts/udisks.py", line 93, in __init__
    '/org/freedesktop/UDisks2')
  File "/usr/lib64/python3.6/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib64/python3.6/site-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib64/python3.6/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib64/python3.6/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib64/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UDisks2 was not provided by any .service files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/scripts/udisks.py", line 171, in get_udisks
    u = UDisks2()
  File "/usr/lib64/python3.6/site-packages/scripts/udisks.py", line 96, in __init__
    raise NoUDisks2()
scripts.udisks.NoUDisks2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib64/python3.6/site-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib64/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.freedesktop.UDisks': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/scripts/udisks.py", line 41, in __init__
    '/org/freedesktop/UDisks'), 'org.freedesktop.UDisks')
  File "/usr/lib64/python3.6/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib64/python3.6/site-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib64/python3.6/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib64/python3.6/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib64/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UDisks was not provided by any .service files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.6/multibootusb", line 105, in <module>
    start_gui()
  File "/usr/lib/python-exec/python3.6/multibootusb", line 49, in start_gui
    from scripts import mbusb_gui
  File "/usr/lib64/python3.6/site-packages/scripts/mbusb_gui.py", line 17, in <module>
    from . import usb
  File "/usr/lib64/python3.6/site-packages/scripts/usb.py", line 19, in <module>
    u = udisks.get_udisks(ver=None)
  File "/usr/lib64/python3.6/site-packages/scripts/udisks.py", line 173, in get_udisks
    u = UDisks()
  File "/usr/lib64/python3.6/site-packages/scripts/udisks.py", line 44, in __init__
    raise NoUDisks1()
scripts.udisks.NoUDisks1
```

`sys-fs/udisks` is not installed on my system, and I prefer not to change that, so perhaps I should give up. But other users may still benefit if the `RDEPEND` variable in multibootusb ebuild is fixed.

**Comment by jorgicio** [comment]
In fact it needs the udisks:2 version, and you're right, so I fixed it and bumped the recent version.
Thanks. Please, resync and try again.

**Comment by fturco** [comment]
I upgraded to `sys-boot/multibootusb-8.8.0` and now I can launch it successfully. Thanks.
